[project]
name = "sql-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.139.2",
    "langchain-core>=1.4.9",
    "pandas>=2.3.3",
    "pydantic-settings>=2.14.2",
    "pytest>=9.1.1",
    "sqlalchemy[asyncio]>=2.0.51",
    "uvicorn>=0.51.0",
]
